services:
  postgres:
    image: postgres:16
    container_name: gh2_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - gh2_network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq_container
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gh2_network

  modsim:
    build: ./modsim
    container_name: modsim-server
    restart: on-failure
    ports:
      - "5020:5020"
      - "9000:9000"
    env_file:
      - ./modsim/.env
    volumes:
      - ./modsim:/app/Modsim
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - gh2_network

  backend:
    build: ./Backend/GH2-Main
    container_name: GH2-Backend
    restart: on-failure
    ports:
      - "7144:7144"
    env_file:
      - ./Backend/GH2-Main/GH2-Main/.env
    depends_on:
      - postgres
      - rabbitmq
      - modsim
    volumes:
      - ./modsim:/shared/modsim
    networks:
      - gh2_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7144/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 50s

  opcua:
    build: ./opcua/server
    container_name: opcua-server
    restart: on-failure
    ports:
      - "4840:4840"
    env_file:
      - ./opcua/server/.env
    depends_on:
      backend:
        condition: service_healthy  # waits until backend /health returns 200
    networks:
      - gh2_network

  opcua_client:
    build: ./opcua/Client
    container_name: opcua-client
    restart: on-failure
    env_file:
      - ./opcua/client/.env
    depends_on:
      - opcua
    networks:
      - gh2_network

  frontend:
    build:
      context: ./Frontend
      dockerfile: dockerfile
    container_name: gh2-frontend
    restart: on-failure
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_API_BASE_URL: http://localhost:7144/api
    networks:
      - gh2_network

networks:
  gh2_network:
    driver: bridge

volumes:
  rabbitmq_data: