version: "3.9"

services:
  # Modbus simulator service
  modsim:
    build: ./modsim
    container_name: modsim-server
    ports:
      - "5020:5020"
      - "9000:9000"
    env_file:
      - ./modsim/.env

  # PostgreSQL database
  postgres:
    image: postgres:16
    container_name: gh2_database
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5433:5432"
    depends_on:
      - modsim

  # RabbitMQ broker
  rabbitmq:
    image: rabbitmq:3.12-management   # includes the management UI
    container_name: rabbitmq_container
    ports:
      - "5672:5672"   # main RabbitMQ port for apps/clients
      - "15672:15672" # management UI port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # OPC UA server
  opcua:
    build: ./opcua/server
    container_name: opcua-server
    ports:
      - "4840:4840"
    env_file:
      - ./opcua/server/.env
    depends_on:
      - rabbitmq
      - postgres

volumes:
  rabbitmq_data:
